services:
  eureka-server:
    build:
      context: .
      dockerfile: infra/eureka-server/Dockerfile
    ports:
      - "8761:8761"

  config-server:
    build:
      context: .
      dockerfile: infra/config-server/Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    volumes:
      - ./config-repo:/app/config-repo

  api-gateway:
    build:
      context: .
      dockerfile: infra/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server


  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server


  product-catalog-service:
    build:
      context: .
      dockerfile: services/product-catalog-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - config-server


  inventory-service:
    build:
      context: .
      dockerfile: services/inventory-service/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - config-server


  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - config-server


  payment-service:
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - config-server


  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - config-server
