CREATE DATABASE ecommerce_user_service;
CREATE DATABASE ecommerce_product_catalog_service;
CREATE DATABASE ecommerce_inventory_service;
CREATE DATABASE ecommerce_order_service;
CREATE DATABASE ecommerce_payment_service;
CREATE DATABASE ecommerce_notification_service;
